---
- name: Upstream Deployment
  hosts: upstream

  vars:
    site: "{{ lookup('env', 'NAME') }}"
    date: "{{ lookup('env', 'DATE') }}"
    home: "/srv/deploys/{{ site }}"
    target: "/srv/deploys/{{ site }}/{{ site }}-{{ date }}"
    current: "/srv/deploys/{{ site }}/{{ site }}-deploy"

  tasks:
    - name: Upstream Fetch
      block:

        - name: Fetching live static content
          synchronize:
            src: "/srv/http/{{ site }}/generators/hugo/content"
            dest: generators/hugo
            mode: pull

        - name: Fetching live image content
          synchronize:
            src: "/srv/http/{{ site }}/public/images"
            dest: public
            mode: pull

        - name: Fetching live video content
          synchronize:
            src: "/srv/http/{{ site }}/public/videos"
            dest: public
            mode: pull

      tags:
        - synchronize

    - name: Upstream Deploy
      block:

        - name: Creating directories
          file:
            path: "{{ item }}"
            state: directory
          with_items:
            - "{{ target }}/public/js"
            - "{{ target }}/public/css"

        - name: Copying previous assets
          shell: |
            cp -r {{ current }}/public/js/*min* {{ target }}/public/js/
            cp -r {{ current }}/public/css/*min* {{ target }}/public/css/
            cp -r {{ current }}/cockpit {{ target }}/
            cp -r {{ current }}/public/images {{ target }}/public/
            cp -r {{ current }}/public/uploads {{ target }}/public/
            cp -r {{ current }}/public/videos {{ target }}/public/
            cp -r {{ current }}/public/download {{ target }}/public/

        - name: Extracting source
          unarchive:
            src: "{{ home }}/{{ site }}.tar.gz"
            dest: "{{ target }}"
            remote_src: yes

        - name: Updating webring
          shell: >
            openring
            -s "https://drewdevault.com/feed.xml"
            -s "https://mxb.dev/feed.xml"
            -s "https://www.taniarascia.com/rss.xml"
            < {{ target }}/generators/openring/template.html
            > {{ target }}/generators/hugo/themes/tdro/layouts/partials/openring.html
          register: output
        - debug: var=output

        - name: Generating static content
          shell: hugo
          args:
            chdir: "{{ target }}/generators/hugo"
          register: output
        - debug: var=output

        - name: Updating image timestamps
          shell: find {{ target }}/public/images -type f -exec touch -d "3 days ago" {} +

        - name: Setting permissions
          file:
            path: "{{ target }}"
            owner: nginx
            group: nginx
            recurse: yes

        - name: Setting immutable files
          file:
            path: "{{ item }}"
            attributes: '+i'
          changed_when: false
          with_items:
            - "{{ target }}/generators/hugo/content/posts/archive.md"
            - "{{ target }}/generators/hugo/content/projects/archive.md"

        - name: Performing an atomic move
          shell: |
            ln -s {{ target }} {{ current }}-deploy-{{ date }}
            mv -Tf {{ current }}-deploy-{{ date }} {{ current }}
          args:
            warn: false

        - name: Setting link permission
          shell: chown -h nginx:nginx {{ current }}

        - name: Removing old deployments
          shell: |
            chattr -i -Rf $(ls -t | awk "NR>8") || true
            rm -rf $(ls -t | awk "NR>8")
          args:
            chdir: "{{ home }}"

      tags:
        - deploy


- name: Downstream Deployment
  hosts: downstream

  vars:
    site: "{{ lookup('env', 'NAME') }}"

  tasks:
    - name: Downstream synchronize
      block:

        - name: Unsetting immutable files
          file:
            path: "{{ item }}"
            attributes: '-i'
          changed_when: false
          with_items:
            - /srv/http/staging/{{ site }}/generators/hugo/content/posts/archive.md
            - /srv/http/staging/{{ site }}/generators/hugo/content/projects/archive.md

        - name: Synchronizing live static content
          synchronize:
            src: generators/hugo/content
            dest: "/srv/http/staging/{{ site }}/generators/hugo"
            rsync_opts:
              - "-zz"

        - name: Generating static content
          shell: hugo
          args:
            chdir: /srv/http/staging/{{ site }}/generators/hugo
          register: output
        - debug: var=output

        - name: Synchronizing live image content
          synchronize:
            src: public/images
            dest: "/srv/http/staging/{{ site }}/public"
            rsync_opts:
              - "-zz"

        - name: Synchronizing live video content
          synchronize:
            src: public/videos
            dest: "/srv/http/staging/{{ site }}/public"
            rsync_opts:
              - "-zz"

        - name: Setting permissions
          file:
            path: "/srv/http/staging/{{ site }}"
            owner: http
            group: http
            recurse: yes

        - name: Setting immutable files
          file:
            path: "{{ item }}"
            attributes: '+i'
          changed_when: false
          with_items:
            - /srv/http/staging/{{ site }}/generators/hugo/content/posts/archive.md
            - /srv/http/staging/{{ site }}/generators/hugo/content/projects/archive.md

      tags:
        - synchronize
