#!/bin/sh -eu
cachedir=$(dirname "$(pwd)")/storage/cache
rm --recursive "${cachedir:?}/"* >/dev/null 2>&1 || { printf "Nothing to invalidate in %s\n" "${cachedir:?}" && exit; }
printf "Cache invalidated in %s\n" "${cachedir:?}"
