---
theme: tdro
baseURL:
languageCode: en-us
title: Thedro Neely

disableKinds: ['404']

taxonomies:
  tag: tags

author:
  name: Thedro Neely

paginate: 3
summaryLength: 20

pygmentsUseClassic: false
pygmentsCodeFences: true
pygmentsUseClasses: true
pygmentsCodeFencesGuessSyntax: true

outputFormats:
  rss:
    baseName: rss
    mediaType: application/xml

outputs:
  home:
  - rss
