---
theme: tdro
baseURL:
languageCode: en-us
title: Thedro Neely

disableKinds: ['404']

taxonomies:
  tag: tags

author:
  name: Thedro Neely

paginate: 3
summaryLength: 20

markup:
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: false
    lineNumbersInTable: false
    noClasses: false
    noHl: false

outputFormats:
  rss:
    baseName: rss
    mediaType: application/xml
  json:
    baseName: index
    mediaType: application/json

outputs:
  home:
  - rss
  - json
